# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 690)
        MainWindow.setMinimumSize(QtCore.QSize(860, 690))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.exportFigPlot = QtWidgets.QPushButton(parent=self.frame)
        self.exportFigPlot.setGeometry(QtCore.QRect(40, 490, 101, 23))
        self.exportFigPlot.setObjectName("exportFigPlot")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(14, 40, 161, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.peakFreqInput = QtWidgets.QLineEdit(parent=self.widget)
        self.peakFreqInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #838383; \n"
"    border-radius: 5px;  /* Apply border-radius */\n"
"}")
        self.peakFreqInput.setObjectName("peakFreqInput")
        self.verticalLayout.addWidget(self.peakFreqInput)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lowFreqInput = QtWidgets.QLineEdit(parent=self.widget)
        self.lowFreqInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #838383; \n"
"    border-radius: 5px;  /* Apply border-radius */\n"
"}")
        self.lowFreqInput.setObjectName("lowFreqInput")
        self.verticalLayout.addWidget(self.lowFreqInput)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.sampleInput = QtWidgets.QLineEdit(parent=self.widget)
        self.sampleInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #838383; \n"
"    border-radius: 5px;  /* Apply border-radius */\n"
"}")
        self.sampleInput.setObjectName("sampleInput")
        self.verticalLayout.addWidget(self.sampleInput)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.dtInput = QtWidgets.QLineEdit(parent=self.widget)
        self.dtInput.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #838383; \n"
"    border-radius: 5px;  /* Apply border-radius */\n"
"}")
        self.dtInput.setObjectName("dtInput")
        self.verticalLayout.addWidget(self.dtInput)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.waveletsComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.waveletsComboBox.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid #838383; \n"
"    border-radius: 5px;  /* Apply border-radius */\n"
"}")
        self.waveletsComboBox.setObjectName("waveletsComboBox")
        self.verticalLayout.addWidget(self.waveletsComboBox)
        self.waveletPlotBtn = QtWidgets.QPushButton(parent=self.widget)
        self.waveletPlotBtn.setObjectName("waveletPlotBtn")
        self.verticalLayout.addWidget(self.waveletPlotBtn)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(639, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.frame_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(800, 16777215))
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_3.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exportFigPlot.setText(_translate("MainWindow", "Exportar imagem"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Frequência Alta</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Frequência Baixa</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Amostras"))
        self.label_4.setText(_translate("MainWindow", "Dt"))
        self.label_5.setText(_translate("MainWindow", "Wavelet"))
        self.waveletPlotBtn.setText(_translate("MainWindow", "Plotar"))
